### ISSUE TITLE
Use env file for connections as opposed to strings?

### ISSUE THREAD

**Issue by GJMcClintock** [slingdata-io/sling-action#1]
Just curious if this is a slightly different version of Sling that is used in the Action?

I tried using it in an action where I copied my env.yml file to `~/.sling/env.yml` after fetching the action, that didn't work. Have also tried using the `SLING_HOME_DIR` variable to no avail. Brew is also failing to install on the linux runner with the latest changes to GitHub actions, so that's not an option either.

I have managed to test that the issue is that my connection URL cannot be parsed when constructed based on special characters in the password, however this would be easier to be able to use the env file vs the string.

**Comment by GJMcClintock** [comment]
Just updating on this:

I got it to work using the connection strings, but I had to manually escape 2 special characters that it appears url.QueryEscape doesn't capture: `-` and `}` happened to be in the string.

Swapping for `%2D` and `%7D` respectively and I got it up and running, but was definitely a hurdle. Having the env.yml option would be easier/more expected

**Comment by flarco** [comment]
Just seeing this, didn't get a notification. Will do, using env.yml would be easier for sure.

**Comment by flarco** [comment]
Done. When 1.1.6 is released, it will support env var `SLING_ENV_YAML`.
